server:
  port: 8081

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: 1234
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
          #当出现 404 错误时, 直接抛出异常
        throw-exception-if-no-handler-found: true
          #静态资源的映射
        static-path-pattern: /static/**
        thymeleaf:
          cache: false
          check-template-location: true
          servlet:
            content-type: text/html
          enabled: true
          encoding: UTF-8
          mode: HTML
          prefix: classpath:/templates/
          suffix: .html
    #activemq:
     #   broker-url: tcp://localhost:61616
     #   userName: admin
     #   password: admin
  #          in-memory: false
  #          pool:
  #              # 是否替换默认的connectionFactory
  #              enabled: false
  #              # 最大连接数
  #              maxConnections: 100
  #
  #          packages:
  #                  # 信任所有的包
  #              trust-all: true
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1234
      database:  0
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
        timeout: 0
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.springbootmybatisdemo.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql